### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by colfin22** [MrNonoss/WeewX-Docker#1]
This is what i get when I try to bring up the docker-compose

`weewx-core    | Traceback (most recent call last):
weewx-core    |   File "/home/weewx/bin/weewxd", line 64, in <module>
weewx-core    |     weewx.engine.main(options, args)
weewx-core    |   File "/home/weewx/bin/weewx/engine.py", line 888, in main
weewx-core    |     engine = engine_class(config_dict)
weewx-core    |   File "/home/weewx/bin/weewx/engine.py", line 72, in __init__
weewx-core    |     self.setupStation(config_dict)
weewx-core    |   File "/home/weewx/bin/weewx/engine.py", line 87, in setupStation
weewx-core    |     stationType = config_dict['Station']['station_type']
weewx-core    |   File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
weewx-core    |     val = dict.__getitem__(self, key)
weewx-core    | KeyError: 'Station'
weewx-core exited with code 1

`

**Comment by edsai** [comment]
I'm getting the same issue. Did you ever resolve it @colfin22?

**Comment by MrNonoss** [comment]
Hi guys,

My apologies, I didn't notice this issue.
It seems to be an issue with your config.
Weewx-core doest not received the correct arguments. 

I tried it again on another machine and it worked well.

**Comment by MrNonoss** [comment]
Closing it since no response from user
